//! End-to-end mock-WAF detection tests.
//!
//! These tests spin up a `wiremock` HTTP server that simulates real WAF
//! response behaviors, then verify the full detect → classify → evasion
//! pipeline against them.  This validates the entire stack without
//! requiring Docker or external infrastructure.
//!
//! # Coverage
//!
//! - Cloudflare challenge page simulation
//! - `ModSecurity` block page simulation
//! - AWS WAF header-only detection
//! - Silent block detection (200 with WAF body markers)
//! - Multiple WAFs behind the same endpoint (ambiguity handling)
//! - Clean (no WAF) response → zero false positives
//! - Response fingerprint drift detection

use reqwest::Client;
use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use wafrift_detect::{
    response_fingerprint::{compare, fingerprint},
    waf_detect::{self, is_blocked_response},
};

/// Helper: make a GET request and return (status, headers, body).
async fn fetch(client: &Client, url: &str) -> (u16, Vec<(String, String)>, Vec<u8>) {
    let resp = client.get(url).send().await.expect("request failed");
    let status = resp.status().as_u16();
    let headers: Vec<(String, String)> = resp
        .headers()
        .iter()
        .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
        .collect();
    let body = resp.bytes().await.expect("body read failed").to_vec();
    (status, headers, body)
}

// ──────────────────────────────────────────────
//  Cloudflare challenge page
// ──────────────────────────────────────────────

#[tokio::test]
async fn e2e_cloudflare_challenge_detected() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/"))
        .respond_with(
            ResponseTemplate::new(503)
                .insert_header("server", "cloudflare")
                .insert_header("cf-ray", "abc123-IAD")
                .set_body_string(
                    "<html><head><title>Just a moment...</title></head>\
                     <body>Checking your browser before accessing. \
                     challenge-platform Ray ID: abc123</body></html>",
                ),
        )
        .mount(&server)
        .await;

    let client = Client::new();
    let (status, headers, body) = fetch(&client, &server.uri()).await;

    // Detection
    let wafs = waf_detect::detect(status, &headers, &body);
    assert!(!wafs.is_empty(), "should detect Cloudflare");
    assert_eq!(wafs[0].name, "Cloudflare");
    assert!(
        wafs[0].confidence >= waf_detect::ACTIONABLE_CONFIDENCE_THRESHOLD,
        "confidence should be high: {}",
        wafs[0].confidence
    );

    // Blocking
    assert!(is_blocked_response(status, &body));

    // Fingerprint should show block markers
    let fp = fingerprint(status, &headers, &body);
    assert!(fp.has_block_markers, "should detect WAF block markers");
}

// ──────────────────────────────────────────────
//  ModSecurity block page
// ──────────────────────────────────────────────

#[tokio::test]
async fn e2e_modsecurity_block_page() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/"))
        .respond_with(
            ResponseTemplate::new(403)
                .insert_header("server", "Apache/2.4.41 (Ubuntu)")
                .set_body_string(
                    "<html><head><title>403 Forbidden</title></head>\
                     <body><h1>Forbidden</h1>\
                     <p>This error was generated by ModSecurity.</p>\
                     <p>ModSecurity rules triggered for your request.</p>\
                     </body></html>",
                ),
        )
        .mount(&server)
        .await;

    let client = Client::new();
    let (status, headers, body) = fetch(&client, &server.uri()).await;

    let wafs = waf_detect::detect(status, &headers, &body);
    assert!(!wafs.is_empty(), "should detect ModSecurity");
    assert_eq!(wafs[0].name, "ModSecurity");

    assert!(is_blocked_response(status, &body));
}

// ──────────────────────────────────────────────
//  AWS WAF — headers-only detection
// ──────────────────────────────────────────────

#[tokio::test]
async fn e2e_aws_waf_headers_only() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/"))
        .respond_with(
            ResponseTemplate::new(403)
                .insert_header("x-amz-id", "BLOCK-12345")
                .set_body_string("<html><body>Request blocked by AWS WAF</body></html>"),
        )
        .mount(&server)
        .await;

    let client = Client::new();
    let (status, headers, body) = fetch(&client, &server.uri()).await;

    let wafs = waf_detect::detect(status, &headers, &body);
    assert!(!wafs.is_empty(), "should detect AWS WAF");
    assert_eq!(wafs[0].name, "AWS Elastic Load Balancer");
}

// ──────────────────────────────────────────────
//  Silent block (HTTP 200, but body replaced)
// ──────────────────────────────────────────────

#[tokio::test]
async fn e2e_silent_block_drift_detection() {
    let server = MockServer::start().await;

    // Baseline: benign response
    Mock::given(method("GET"))
        .and(path("/baseline"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/html")
                .set_body_string(
                    "<html><head><title>My App</title></head>\
                     <body>Search results for: test query</body></html>",
                ),
        )
        .mount(&server)
        .await;

    // Silently blocked: same 200, but body replaced with WAF page
    Mock::given(method("GET"))
        .and(path("/blocked"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/html")
                .set_body_string(
                    "<html><head><title>Access Denied</title></head>\
                     <body>Your request has been blocked by our web application firewall. \
                     If you believe this is an error, please contact support.</body></html>",
                ),
        )
        .mount(&server)
        .await;

    let client = Client::new();

    let (s1, h1, b1) = fetch(&client, &format!("{}/baseline", server.uri())).await;
    let (s2, h2, b2) = fetch(&client, &format!("{}/blocked", server.uri())).await;

    let fp_baseline = fingerprint(s1, &h1, &b1);
    let fp_blocked = fingerprint(s2, &h2, &b2);

    let drift = compare(&fp_baseline, &fp_blocked);

    assert!(
        drift.score >= 0.4,
        "drift score should be significant: {}",
        drift.score
    );
    assert!(drift.likely_blocked, "should detect as likely blocked");
    assert!(
        drift.changed.contains(&"block_markers_appeared"),
        "should flag block markers as a changed component"
    );
}

// ──────────────────────────────────────────────
//  Clean response — zero false positives
// ──────────────────────────────────────────────

#[tokio::test]
async fn e2e_clean_response_no_false_positive() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("server", "nginx/1.20.0")
                .insert_header("content-type", "text/html; charset=utf-8")
                .set_body_string(
                    "<html><head><title>Welcome</title></head>\
                     <body><h1>Welcome to our application</h1>\
                     <p>Everything is working normally.</p></body></html>",
                ),
        )
        .mount(&server)
        .await;

    let client = Client::new();
    let (status, headers, body) = fetch(&client, &server.uri()).await;

    let wafs = waf_detect::detect(status, &headers, &body);
    assert!(
        wafs.is_empty(),
        "clean response should not trigger WAF detection, got: {wafs:?}"
    );

    assert!(!is_blocked_response(status, &body));

    let fp = fingerprint(status, &headers, &body);
    assert!(!fp.has_block_markers, "should not have WAF block markers");
}

// ──────────────────────────────────────────────
//  Akamai Kona with Reference ID in body
// ──────────────────────────────────────────────

#[tokio::test]
async fn e2e_akamai_kona_detection() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/"))
        .respond_with(
            ResponseTemplate::new(403)
                .insert_header("server", "AkamaiGHost")
                .insert_header("x-akamai-transformed", "9 12345 0")
                .set_body_string(
                    "<html><body><h1>Access Denied</h1>\
                     <p>You don't have permission to access this resource.</p>\
                     <p>Reference #18.abc123def.1234567890.456</p>\
                     </body></html>",
                ),
        )
        .mount(&server)
        .await;

    let client = Client::new();
    let (status, headers, body) = fetch(&client, &server.uri()).await;

    let wafs = waf_detect::detect(status, &headers, &body);
    assert!(!wafs.is_empty(), "should detect Akamai Kona");
    assert_eq!(wafs[0].name, "Kona SiteDefender");
}

// ──────────────────────────────────────────────
//  Incapsula — cookie-based detection
// ──────────────────────────────────────────────

#[tokio::test]
async fn e2e_incapsula_cookie_detection() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("x-cdn", "Incapsula")
                .insert_header(
                    "set-cookie",
                    "visid_incap_1234=abcdef123; path=/; domain=.example.com",
                )
                .insert_header("x-iinfo", "10-12345678-0 0NNN RT(0")
                .set_body_string("<html><body>Protected content</body></html>"),
        )
        .mount(&server)
        .await;

    let client = Client::new();
    let (status, headers, body) = fetch(&client, &server.uri()).await;

    let wafs = waf_detect::detect(status, &headers, &body);
    assert!(!wafs.is_empty(), "should detect Incapsula");
    assert_eq!(wafs[0].name, "Incapsula");
}

// ──────────────────────────────────────────────
//  Benign → Blocked fingerprint drift
// ──────────────────────────────────────────────

#[tokio::test]
async fn e2e_fingerprint_identical_responses_zero_drift() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/stable"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/html")
                .set_body_string("<html><body>Stable content</body></html>"),
        )
        .mount(&server)
        .await;

    let client = Client::new();
    let url = format!("{}/stable", server.uri());

    let (s1, h1, b1) = fetch(&client, &url).await;
    let (s2, h2, b2) = fetch(&client, &url).await;

    let fp1 = fingerprint(s1, &h1, &b1);
    let fp2 = fingerprint(s2, &h2, &b2);

    let drift = compare(&fp1, &fp2);
    assert!(
        drift.score < f64::EPSILON,
        "identical responses should have zero drift, got: {}",
        drift.score
    );
    assert!(!drift.likely_blocked);
}

// ──────────────────────────────────────────────
//  Benign → 403 status change drift
// ──────────────────────────────────────────────

#[tokio::test]
async fn e2e_status_change_detected_as_drift() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/benign"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/html")
                .set_body_string("<html><body>OK</body></html>"),
        )
        .mount(&server)
        .await;

    Mock::given(method("GET"))
        .and(path("/attack"))
        .respond_with(
            ResponseTemplate::new(403)
                .insert_header("content-type", "text/html")
                .set_body_string("<html><body>Forbidden. Access Denied.</body></html>"),
        )
        .mount(&server)
        .await;

    let client = Client::new();
    let (s1, h1, b1) = fetch(&client, &format!("{}/benign", server.uri())).await;
    let (s2, h2, b2) = fetch(&client, &format!("{}/attack", server.uri())).await;

    let fp1 = fingerprint(s1, &h1, &b1);
    let fp2 = fingerprint(s2, &h2, &b2);

    let drift = compare(&fp1, &fp2);
    assert!(
        drift.score >= 0.3,
        "status change should register drift: {}",
        drift.score
    );
    assert!(drift.changed.contains(&"status_code"));
    assert!(drift.likely_blocked);
}
