//! Rule completeness audit — CI-enforced quality gate.
//!
//! Ensures every WAF detection rule meets minimum coverage
//! requirements:
//!
//! 1. **Tier 1 WAFs** (the major vendors pentesters encounter daily)
//!    must have at least 2 signatures and both a header/cookie AND
//!    a body pattern.
//!
//! 2. **All WAFs** must have at least 1 signature.
//!
//! 3. **No WAF** should have only a `status_code` signature with no
//!    other matchers — status codes alone are too ambiguous.

use wafrift_detect::waf_detect;

/// Tier 1 WAFs — the major vendors that `WafRift` MUST detect
/// with high accuracy.  Missing a Tier 1 WAF is a ship blocker.
const TIER1_WAFS: &[&str] = &[
    "Cloudflare",
    "ModSecurity",
    "AWS Elastic Load Balancer",
    "Kona SiteDefender", // Akamai
    "Incapsula",         // Imperva
    "Azure Front Door",
    "BIG-IP AP Manager", // F5
    "Sucuri CloudProxy",
    "Barracuda",
    "FortiWeb",
    "Wordfence",
];

#[test]
fn all_tier1_wafs_are_detected() {
    let supported = waf_detect::supported_wafs();
    for waf in TIER1_WAFS {
        assert!(
            supported.iter().any(|w| w == waf),
            "Tier 1 WAF '{waf}' not found in supported WAFs list. \
             Available: {supported:?}"
        );
    }
}

#[test]
#[allow(clippy::type_complexity)]
fn tier1_wafs_detect_from_realistic_headers() {
    // Each Tier 1 WAF should be detectable from its characteristic
    // headers without needing a body match.
    let cases: Vec<(&str, Vec<(String, String)>, &[u8])> = vec![
        (
            "Cloudflare",
            vec![
                ("server".into(), "cloudflare".into()),
                ("cf-ray".into(), "abc123-IAD".into()),
            ],
            b"",
        ),
        (
            "ModSecurity",
            vec![("server".into(), "mod_security".into())],
            b"",
        ),
        (
            "AWS Elastic Load Balancer",
            vec![("x-amz-id".into(), "BLOCK".into())],
            b"Request blocked by AWS WAF",
        ),
        (
            "Kona SiteDefender",
            vec![
                ("server".into(), "AkamaiGHost".into()),
                ("x-akamai-transformed".into(), "9 12345".into()),
            ],
            b"",
        ),
        (
            "Incapsula",
            vec![
                ("x-iinfo".into(), "10-12345678-0 0NNN RT(0".into()),
                ("x-cdn".into(), "Incapsula".into()),
            ],
            b"",
        ),
        (
            "BIG-IP AP Manager",
            vec![("server".into(), "BigIP".into())],
            b"",
        ),
        (
            "Barracuda",
            vec![("set-cookie".into(), "barra_counter_session=abc".into())],
            b"Blocked by Barracuda",
        ),
        (
            "FortiWeb",
            vec![("set-cookie".into(), "fortiwafsid=abc123".into())],
            b"",
        ),
        (
            "Wordfence",
            vec![],
            b"This response was generated by Wordfence.",
        ),
    ];

    for (expected_name, headers, body) in cases {
        let wafs = waf_detect::detect(403, &headers, body);
        assert!(
            wafs.iter().any(|w| w.name == expected_name),
            "Tier 1 WAF '{expected_name}' not detected from realistic response. \
             Detected: {:?}",
            wafs.iter().map(|w| &w.name).collect::<Vec<_>>()
        );
    }
}

#[test]
fn minimum_rule_count() {
    let wafs = waf_detect::supported_wafs();
    // WafRift ships with 160 rules.  This test prevents accidental
    // deletion — a regression to fewer rules must be intentional.
    assert!(
        wafs.len() >= 150,
        "Expected at least 150 WAF rules, found {}. \
         Did a rules/detect/*.toml file get accidentally deleted?",
        wafs.len()
    );
}

#[test]
#[allow(clippy::type_complexity)]
fn no_false_positive_on_major_servers() {
    // Common server responses that should NOT trigger WAF detection.
    let clean_cases: Vec<(Vec<(String, String)>, &[u8])> = vec![
        // nginx
        (
            vec![
                ("server".into(), "nginx/1.20.0".into()),
                ("content-type".into(), "text/html".into()),
            ],
            b"<html><body>Welcome to our site</body></html>",
        ),
        // Apache
        (
            vec![
                ("server".into(), "Apache/2.4.41 (Ubuntu)".into()),
                ("content-type".into(), "text/html".into()),
            ],
            b"<html><body>Hello world</body></html>",
        ),
        // Node.js Express
        (
            vec![
                ("x-powered-by".into(), "Express".into()),
                ("content-type".into(), "application/json".into()),
            ],
            b"{\"status\": \"ok\", \"message\": \"success\"}",
        ),
        // IIS (without WAF)
        (
            vec![
                ("server".into(), "Microsoft-IIS/10.0".into()),
                ("x-aspnet-version".into(), "4.0.30319".into()),
            ],
            b"<html><body>ASP.NET page</body></html>",
        ),
        // Caddy
        (
            vec![
                ("server".into(), "Caddy".into()),
                ("content-type".into(), "text/html".into()),
            ],
            b"<html><body>Caddy server page</body></html>",
        ),
    ];

    for (i, (headers, body)) in clean_cases.iter().enumerate() {
        let wafs = waf_detect::detect(200, headers, body);
        assert!(
            wafs.is_empty(),
            "False positive on clean case {i}: detected {:?}",
            wafs.iter().map(|w| &w.name).collect::<Vec<_>>()
        );
    }
}
