//! Detection throughput benchmark.
//!
//! Measures WAF detection performance across realistic response
//! scenarios, establishing the baseline for performance regression
//! gating.
//!
//! Run with:
//! ```bash
//! cargo bench -p wafrift-detect -- detect_throughput
//! ```

use criterion::{BenchmarkId, Criterion, black_box, criterion_group, criterion_main};
use wafrift_detect::{
    response_fingerprint::{compare, fingerprint},
    waf_detect,
};

/// Realistic Cloudflare challenge response.
fn cloudflare_response() -> (u16, Vec<(String, String)>, Vec<u8>) {
    (
        503,
        vec![
            ("server".into(), "cloudflare".into()),
            ("cf-ray".into(), "abc123-IAD".into()),
            ("content-type".into(), "text/html; charset=UTF-8".into()),
        ],
        b"<html><head><title>Just a moment...</title></head>\
          <body class=\"no-js\">Checking your browser before accessing. \
          challenge-platform <div id=\"cf-spinner-please-wait\">Please wait...</div>\
          DDoS protection by Cloudflare. Ray ID: abc123</body></html>"
            .to_vec(),
    )
}

/// Realistic `ModSecurity` block page.
fn modsecurity_response() -> (u16, Vec<(String, String)>, Vec<u8>) {
    (
        403,
        vec![
            ("server".into(), "Apache/2.4.41".into()),
            ("content-type".into(), "text/html".into()),
        ],
        b"<html><head><title>403 Forbidden</title></head>\
          <body><h1>Forbidden</h1>\
          <p>This error was generated by ModSecurity. \
          OWASP ModSecurity Core Rule Set triggered. \
          Rules of the mod_security module blocked this request.</p>\
          </body></html>"
            .to_vec(),
    )
}

/// Clean response — should produce zero detections.
fn clean_response() -> (u16, Vec<(String, String)>, Vec<u8>) {
    (
        200,
        vec![
            ("server".into(), "nginx/1.20.0".into()),
            ("content-type".into(), "text/html; charset=utf-8".into()),
            ("x-request-id".into(), "abc123".into()),
        ],
        b"<html><head><title>My Application</title></head>\
          <body><h1>Welcome</h1><p>This is a normal web page with \
          regular content. Nothing unusual here. Lorem ipsum dolor sit amet, \
          consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut \
          labore et dolore magna aliqua.</p></body></html>"
            .to_vec(),
    )
}

/// Large body (~4 KiB, the detection window size).
fn large_body_response() -> (u16, Vec<(String, String)>, Vec<u8>) {
    let mut body = Vec::with_capacity(4096);
    body.extend_from_slice(b"<html><body>");
    // Fill with realistic HTML content up to ~4 KiB.
    while body.len() < 3900 {
        body.extend_from_slice(
            b"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. \
              Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.</p>",
        );
    }
    body.extend_from_slice(b"</body></html>");
    (
        200,
        vec![
            ("server".into(), "nginx".into()),
            ("content-type".into(), "text/html".into()),
        ],
        body,
    )
}

#[allow(clippy::type_complexity)]
fn bench_waf_detection(c: &mut Criterion) {
    let mut group = c.benchmark_group("waf_detection");

    let cases: Vec<(&str, (u16, Vec<(String, String)>, Vec<u8>))> = vec![
        ("cloudflare_503", cloudflare_response()),
        ("modsecurity_403", modsecurity_response()),
        ("clean_200", clean_response()),
        ("large_body_4k", large_body_response()),
    ];

    for (name, (status, headers, body)) in &cases {
        group.bench_with_input(
            BenchmarkId::new("detect", name),
            &(status, headers, body),
            |b, (status, headers, body)| {
                b.iter(|| {
                    let result = waf_detect::detect(
                        black_box(**status),
                        black_box(headers),
                        black_box(body),
                    );
                    black_box(result)
                });
            },
        );
    }

    group.finish();
}

fn bench_fingerprint(c: &mut Criterion) {
    let mut group = c.benchmark_group("fingerprint");

    let (status, headers, body) = cloudflare_response();
    group.bench_function("create", |b| {
        b.iter(|| {
            let fp = fingerprint(black_box(status), black_box(&headers), black_box(&body));
            black_box(fp)
        });
    });

    let (s1, h1, b1) = clean_response();
    let (s2, h2, b2) = cloudflare_response();
    let fp1 = fingerprint(s1, &h1, &b1);
    let fp2 = fingerprint(s2, &h2, &b2);

    group.bench_function("compare_drift", |b| {
        b.iter(|| {
            let drift = compare(black_box(&fp1), black_box(&fp2));
            black_box(drift)
        });
    });

    group.finish();
}

fn bench_blocking_check(c: &mut Criterion) {
    let mut group = c.benchmark_group("blocking");

    let (_, _, body) = cloudflare_response();
    group.bench_function("waf_body_4k", |b| {
        b.iter(|| {
            let result = waf_detect::is_blocked_response(black_box(503), black_box(&body));
            black_box(result)
        });
    });

    let (_, _, body) = clean_response();
    group.bench_function("clean_body_small", |b| {
        b.iter(|| {
            let result = waf_detect::is_blocked_response(black_box(200), black_box(&body));
            black_box(result)
        });
    });

    let (_, _, body) = large_body_response();
    group.bench_function("large_body_4k", |b| {
        b.iter(|| {
            let result = waf_detect::is_blocked_response(black_box(200), black_box(&body));
            black_box(result)
        });
    });

    group.finish();
}

criterion_group!(
    benches,
    bench_waf_detection,
    bench_fingerprint,
    bench_blocking_check
);
criterion_main!(benches);
