[[waf]]
name = "KeyCDN"
vendor = "KeyCDN"
confidence_threshold = 0.3
evasions = ["CaseAlternation", "SqlCommentInsertion", "DoubleUrlEncode", "ContentTypeSwitch"]
source = "WAFW00F:keycdn"
[[waf.signature]]
  header_name = "server"
  header_regex = "KeyCDN"
  weight = 0.5
