schema = 1

[[case]]
id = "tautology_or"
class = "ldap"
payload = "*)(uid=*))(|(uid=*"

[[case]]
id = "tautology_and"
class = "ldap"
payload = "*)(&(objectClass=*"

[[case]]
id = "wildcard_anon"
class = "ldap"
payload = "*)(cn=*))(|(cn=*"

[[case]]
id = "boolean_filter"
class = "ldap"
payload = "*)(uid=admin"
