//! Build script: compile community-contributed marker tables (`rules/markers/*.toml`)
//! into a Rust source file picked up by `signal_body_marker.rs` and `signal_headers.rs`.
//!
//! Each TOML file is a flat data file — adding a marker is a one-line PR with
//! zero Rust knowledge. The build script reads them, emits `OUT_DIR/markers_data.rs`,
//! and the consumers `include!` it. No runtime parse cost.

use serde::Deserialize;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct Patterns {
    #[serde(default)]
    patterns: Vec<String>,
    #[serde(default)]
    prefixes: Vec<String>,
    #[serde(default)]
    categories: Vec<String>,
    #[serde(default)]
    vendors: Vec<String>,
    #[serde(default)]
    names: Vec<String>,
}

#[derive(Deserialize)]
struct WafHeaders {
    #[serde(default)]
    entry: Vec<WafHeaderEntry>,
}

#[derive(Deserialize)]
struct WafHeaderEntry {
    name: String,
    value_pattern: String,
    description: String,
}

fn read_strings(path: &Path, field: fn(Patterns) -> Vec<String>) -> Vec<String> {
    let raw = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let parsed: Patterns =
        toml::from_str(&raw).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));
    field(parsed)
}

fn emit_str_array(out: &mut String, name: &str, values: &[String]) {
    out.push_str(&format!("pub const {name}: &[&str] = &[\n"));
    for v in values {
        out.push_str(&format!("    {v:?},\n"));
    }
    out.push_str("];\n\n");
}

fn main() {
    let rules_dir = Path::new("rules/markers");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("markers_data.rs");

    let mut out = String::with_capacity(8192);
    out.push_str("// Auto-generated by build.rs from rules/markers/*.toml — do not edit.\n\n");

    let block = read_strings(&rules_dir.join("block.toml"), |p| p.patterns);
    let challenge = read_strings(&rules_dir.join("challenge.toml"), |p| p.patterns);
    let rate_limit = read_strings(&rules_dir.join("rate_limit.toml"), |p| p.patterns);
    let success = read_strings(&rules_dir.join("success.toml"), |p| p.patterns);
    let rule_id_prefixes = read_strings(&rules_dir.join("rule_id_prefixes.toml"), |p| p.prefixes);
    let rule_categories = read_strings(&rules_dir.join("rule_categories.toml"), |p| p.categories);
    let vendors = read_strings(&rules_dir.join("vendors.toml"), |p| p.vendors);
    let block_header_names = read_strings(&rules_dir.join("block_headers.toml"), |p| p.names);

    emit_str_array(&mut out, "BLOCK_MARKERS", &block);
    emit_str_array(&mut out, "CHALLENGE_MARKERS", &challenge);
    emit_str_array(&mut out, "RATE_LIMIT_MARKERS", &rate_limit);
    emit_str_array(&mut out, "SUCCESS_MARKERS", &success);
    emit_str_array(&mut out, "RULE_ID_PREFIXES", &rule_id_prefixes);
    emit_str_array(&mut out, "RULE_CATEGORIES", &rule_categories);
    emit_str_array(&mut out, "VENDOR_NAMES", &vendors);
    emit_str_array(&mut out, "BLOCK_HEADER_NAMES", &block_header_names);

    // ── waf_headers.toml: structured 3-tuples ──
    let raw =
        fs::read_to_string(rules_dir.join("waf_headers.toml")).expect("read waf_headers.toml");
    let parsed: WafHeaders = toml::from_str(&raw).expect("parse waf_headers.toml");
    out.push_str("pub const WAF_HEADERS: &[(&str, &str, &str)] = &[\n");
    for e in &parsed.entry {
        out.push_str(&format!(
            "    ({:?}, {:?}, {:?}),\n",
            e.name, e.value_pattern, e.description
        ));
    }
    out.push_str("];\n");

    fs::write(&out_path, out).expect("write markers_data.rs");

    println!("cargo::rerun-if-changed=rules/markers");
    for entry in fs::read_dir(rules_dir).expect("read rules/markers dir") {
        let path = entry.expect("dir entry").path();
        println!("cargo::rerun-if-changed={}", path.display());
    }
}
