.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH probe 1  "probe " 
.SH NAME
probe \- Generate differential analysis probes
.SH SYNOPSIS
\fBprobe\fR [\fB\-\-quick\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Generate differential analysis probes
.SH OPTIONS
.TP
\fB\-\-quick\fR
Generate a smaller probe set
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
