[[waf]]
name = "ArvanCloud"
vendor = "ArvanCloud"
confidence_threshold = 0.3
evasions = ["CaseAlternation", "SqlCommentInsertion", "DoubleUrlEncode", "ContentTypeSwitch"]
source = "WAFW00F:arvancloud"
[[waf.signature]]
  header_name = "server"
  header_regex = "ArvanCloud"
  weight = 0.5
