[[waf]]
name = "Astra"
vendor = "Czar Securities"
confidence_threshold = 0.3
evasions = ["CaseAlternation", "SqlCommentInsertion", "DoubleUrlEncode", "ContentTypeSwitch"]
source = "WAFW00F:astra"
[[waf.signature]]
  body_regex = "astrawebsecurity\\.freshdesk\\.com"
  weight = 0.4
[[waf.signature]]
  body_regex = "www\\.getastra\\.com/assets/images"
  weight = 0.4
