[[waf]]
name = "DenyALL"
vendor = "Rohde & Schwarz CyberSecurity"
confidence_threshold = 0.3
evasions = ["CaseAlternation", "SqlCommentInsertion", "DoubleUrlEncode", "ContentTypeSwitch"]
source = "WAFW00F:denyall"
[[waf.signature]]
  status_code = 200
  weight = 0.2
