[[waf]]
name = "Azure Front Door"
vendor = "Microsoft"
confidence_threshold = 0.3
evasions = ["CaseAlternation", "SqlCommentInsertion", "DoubleUrlEncode", "ContentTypeSwitch"]
source = "WAFW00F:frontdoor"
[[waf.signature]]
  header_name = "x-azure-ref"
  header_regex = ".+?"
  weight = 0.5
