[[waf]]
name = "IndusGuard"
vendor = "Indusface"
confidence_threshold = 0.3
evasions = ["CaseAlternation", "SqlCommentInsertion", "DoubleUrlEncode", "ContentTypeSwitch"]
source = "WAFW00F:indusguard"
[[waf.signature]]
  header_name = "server"
  header_regex = "IF_WAF"
  weight = 0.5
[[waf.signature]]
  body_regex = "This website is secured against online attacks. Your request was blocked"
  weight = 0.4
