//! Build script: compile community-contributed polyglot payloads
//! (`rules/polyglot/polyglots.toml`) into a Rust source file.

use serde::Deserialize;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct PolyglotsFile {
    #[serde(default)]
    polyglot: Vec<RawPolyglot>,
}

#[derive(Deserialize)]
struct RawPolyglot {
    payload: String,
    contexts: Vec<String>,
    description: String,
}

fn main() {
    let in_path = Path::new("rules/polyglot/polyglots.toml");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("polyglots_data.rs");

    let raw =
        fs::read_to_string(in_path).unwrap_or_else(|e| panic!("read {}: {e}", in_path.display()));
    let parsed: PolyglotsFile =
        toml::from_str(&raw).unwrap_or_else(|e| panic!("parse {}: {e}", in_path.display()));

    let mut out = String::with_capacity(8192);
    out.push_str(
        "// Auto-generated by build.rs from rules/polyglot/polyglots.toml — do not edit.\n\n",
    );
    out.push_str("pub(crate) const POLYGLOTS_RAW: &[(&str, &[&str], &str)] = &[\n");
    for p in &parsed.polyglot {
        out.push_str("    (");
        out.push_str(&format!("{:?}, ", p.payload));
        out.push_str("&[");
        for (i, ctx) in p.contexts.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{ctx:?}"));
        }
        out.push_str("], ");
        out.push_str(&format!("{:?}", p.description));
        out.push_str("),\n");
    }
    out.push_str("];\n");

    fs::write(&out_path, out).expect("write polyglots_data.rs");
    println!("cargo::rerun-if-changed={}", in_path.display());
}
